---
- name: debug testing
  hosts: localhost
  gather_facts: False
  vars:
  - names:
    - Vinny
    - Bob
    - Alice
    - Robert
  tasks:
  - name: debug
    debug:
      msg: Hello {{ item }}, nice to meet you again.
    loop: "{{ names }}"
