---
- name: Push Nagios NCPA log exclude files to linux hosts
  hosts: linux
  gather_facts: False
  become: True
  vars:
    files:
      - check_logfiles_messages.cfg
      - check_logfiles_secure.cfg
      - check_logfiles_secure_logon.cfg

  tasks:

    - name: Copy exclude files
      copy:
        src: ./files/{{ item }}
        dest: /usr/local/ncpa/plugins/{{ item }}
        owner: root
        group: nagios
        mode: '0755'
      loop: "{{ files }}"
