---
- name: Push Nagios NCPA Config File
  hosts: all
  gather_facts: False
  become: False

  tasks:

  - name: copy nagios exclude files
    win_copy:
      src: ./files/{{ item }}
      dest: 'C:\Program Files (x86)\Nagios\NCPA\plugins\{{ item }}'
    loop:
      - check_eventlog_exclude.txt
    #  - logon_exclude.txt
