---
- name: Push Nagios NCPA Config File
  hosts: Windows
  gather_facts: False
  become: False

  tasks:

  - name: copy nagios eventlog exclude file
    win_copy:
      src: ./files/check_eventlog_exclude.txt 
      dest: 'C:\Program Files (x86)\Nagios\NCPA\plugins\check_eventlog_exclude.txt'
