- name: Install Red Hat Packages
  hosts: Vintest
  gather_facts: False
  become: True
  tasks:
  - name: Yum install
    yum:
      name:
      - tcpdump
      - lsof
      - nmap
      - vim-enhanced
      - zsh
      state: present
